### ISSUE TITLE
Add a check to check all common variables are in all the datasets 

### ISSUE THREAD

**Issue by statasaurus** [atorus-research/metacore#1]

**Comment by TeMeta** [comment]
Does this enhancement indicate that the common variables will be available as explicit entries in the metadata for that dataset?

I highly-recommend taking this approach (scenario #1) to avoid a headache later.

**Scenario #1:** manage the common variables in the _metadata_ when they are flagged in ADSL (i.e. add/remove from the other datasets, then run this check). Downstream functions and apps handle the variables as-is.

**Scenario #2:** common variables are only in ADSL metadata. Downstream functions and apps have to query/merge/handle these common variables from ADSL.

**Comment by statasaurus** [comment]
Implemented in metatools
