### ISSUE TITLE
Potentially delete dev and just use main as the dev branch 

### ISSUE THREAD

**Issue by statasaurus** [atorus-research/metacore#103]
@mstackhouse I would like to propose getting rid of dev and instead just use the main as the dev branch. It is fairly standard within the R world to use can as a stable release so I don't think it is useful to have a stable main as well. Plus it leads to miscommunication. I think after this 1.3 release we delete

**Comment by mstackhouse** [comment]
@statasaurus  given that you're the primary maintainer, if that's your preference I don't have an issue with making the change.

**Comment by statasaurus** [comment]
Okay I will action this at the next release
