### ISSUE TITLE
`key_seq` is not supported in `spec_type_to_ds_vars()` unless it is in an external sheet

### ISSUE THREAD

**Issue by kodesiba** [atorus-research/metacore#11]
When using `spec_type_to_ds_vars()` with the `key_seq` variable in the main sheet it will not get passed through to `create_table` and will not get added on later.  It looks as though only the `cols` argument is passed to `create_table()` therefore the `key_seq` variable will not get passed through and added on.

**Comment by statasaurus** [comment]
All you need to do is move your key_seq in the cols argument
