### ISSUE TITLE
Allow suppression of message from `drop_unspec_vars()`

### ISSUE THREAD

**Issue by bms63** [atorus-research/metacore#111]
Is it possible to add an option to suppress this message?  It is _super nice_ to have this print out while developing the ADaM, but towards the end of programming the ADaM I don't really need this anymore to be printed out.  Be nice to have cleaner log file

![image](https://github.com/user-attachments/assets/40d90003-ea53-4dae-842e-1489cd522d67)

**Comment by statasaurus** [comment]
This is in the wrong package. But it looks like you put the issue in metatools so I am going to close this
