### ISSUE TITLE
Demo data return functions

### ISSUE THREAD

**Issue by mstackhouse** [atorus-research/metacore#33]
@statasaurus can we put in a function that returns that Pilot AdaM metacore object? We have metacore_example() which gives file paths. But what about like a load_metacore_adam_example() or something much less verbose that returns the demo object?

I was looking for this when I was unit testing on metatools. It would even be a nice touch to have the individual tables as dataframes available so you can pull them into memory quick and create a metacore object.

**Comment by statasaurus** [comment]
so load(metacore_example("pilot_ADaM.rda")) is the faster version. Given we have this do you thing we need load_metacore_adam_example()? If you feel strongly we can add it

**Comment by mstackhouse** [comment]
@statasaurus I don't have strong feelings. So that's fine. We should just have it in the example code of the `metacore_example()` docs and probably in a vignette.
