### ISSUE TITLE
esimms_build_specification_readers

### ISSUE THREAD

**Issue by esimms999** [atorus-research/metacore#43]
/vignettes/Building_Specification_readers.Rmd:

- "By default metacore can read in specification that ..." -> "By default metacore can read in specifications that ..."
- "Therefore we will have to build bespoke ..." -> "Therefore we will have to build a bespoke ..."
- "ds_sep: Contains dataset ..." -> "ds_spec: Contains dataset ..."
- "The ds_vars table has 5 columns:" -> "The ds_vars table has 7 columns:"
- "Now we know what we need we can ..." -> "Now that we know what we need, we can ..."
- "... the where information on different ..." -> "... the where information on a different ..."
- code block shows warning message with typo; this is due to line 129 of /R/validators.R (see below)

---------

Line 129 of /R/validators.R:

- "Warning: The following variables hace code ids not found in the ..." -> "Warning: The following variables have code ids not found in the ..."

**Comment by statasaurus** [comment]
Corrected in dev branch
