### ISSUE TITLE
Importing from Excel specs (P21 formats) and define-xml 

### ISSUE THREAD

**Issue by CedricDavister** [atorus-research/metacore#49]
Hi, I have been testing/started considering the metacore/metatools packages for ADaM work and downloaded the latest versions from github this week, following the readme instructions. I would like to report potential issues related to building metacore from Excel specs (following the P21 Excel file formats) and related to importing from define-xml. I have regrouped in one post as these are all potential issues related to importing functionality.

1) spec_to_metacore (using the old P21 Excel file format - with a WhereClauses sheet): issue with importing composite where clauses (i.e. conjunctive clauses) like: PARAMCD EQ "CUMPLDOS" and AVISIT EQ "POST TREATMENT FOLLOW-UP 2". Such a composite Where clause is split into 2 records in the WhereClauses sheet, bearing the same ID and holding each a base clause. After importing, 2 records are created in VALUE_SPEC, one for each base clause. I would expect a single record instead in VALUE_SPEC with the composite clause rebuilt. Likely the issue is in spec_type_to_value_spec(... where_sep_sheet = TRUE... ).

2) define_to_metacore : similar issues with importing composite where clauses. In define-xml, such where clauses are also split into basic clauses. While importing from define, one record is created in VALUE_DESC but only the first part of the composite where clause is imported, the rest is ignored. So, the issue is related but slightly different than 1).

3) spec_to_metacore (using the new P21 Excel file format - without the WhereClauses sheet and the where clauses directly in ValueLevel): fails to import and throws errors. However, import works following the stepwise approach with the individual spec_type_to_ functions. I assume spec_to_metacore is tweaked towards the old P21 Excel file format. However, considering that the new P21 Excel file format is now used in recent releases of the P21 Enterprise and Community tools, it would be nice that the function can import directly the newer format as well. Note: here the composite where clauses import well in VALUE_SPEC - which may be expected as they are already on a single line in the input file.

4) spec_to_metacore: In the P21 Excel file format, for variables/VLM with Origin = "Predecessor", the details are stored in the Predecessor column, for variables with Origin = "Assigned", the details are stored in the Comment column. The import function only handles Origin = "Derived" and reads the details from the Method column into DERIVATIONS. The predecessor and assignment details are lost during import. Looking at the metacore_example("pilot_ADaM.rda"), all the predecessor and assignment details are stored in the DERIVATIONS table. Technically as a VALUE_SPEC record can have only a single Origin, I understand that the origin details may always be stored in the DERIVITIONS table whatever the Origin - as shown in pilot_ADaM.rda. But then it would make sense for spec_to_metacore (or spec_type_to_value_spec) to be able to map the Predecessor column or Comment column into the DERIVATIONS table as well, according to the value of Origin.

5) define_to_metacore: faces a similar issue to 4) when Origin="Predecessor" or "Assigned", the detailed origin description is also lost and not stored in the DERIVATIONS table.

**Comment by statasaurus** [comment]
The where clauses might be a bit complicated, but the other stuff I can do relatively quickly if I have examples. @mstackhouse do have anything I could use? The CDISC pilot doesn't use the Origin="Predecessor" notation so I can't use that. 

But, for the where clause I just want to check one thing, will the composite always be an "and"? If so that isn't actually such a big change. Again it would be helpful to have an example of this in a spec and a define so I can correct it. The

**Comment by mstackhouse** [comment]
From the Define 2.1.3 Standard:

> ## 4.5.1 Where Clauses for Value-level Metadata
> 
> Where Clauses are used to describe the conditions under which the definition of a value applies in a machine-readable form. Each Value definition may have a Where clauses attached to it to describe when that Value applies. The Where Clause mechanism allows the definition of slices. _Slices_ are subsets of a dataset that typically include a subset of the dataset rows which share similar metadata.
> 
> Where Clauses can contain references to:
> 1. Variables in the current dataset
> 2. Variables in other subject-level datasets within the same metadata version in a Define-XML document. In this case, the implied dataset join should be documented in a comment attached to the WhereClauseDef.
> Note: In the current specification, there is no mechanism for machine-readable join specifications. Therefore the Comment functionality is intended to document the implied join.
> 
> **Where Clauses define a condition by using one or more Range Checks.**
> **- Where there are multiple Range Checks, the condition is defined as the logical AND of all the Range Checks**
> **- If there are multiple Where Clauses, the condition is defined as the logical OR of the Where Clauses**

@statasaurus So it's not just AND, it's also OR conditions with the where clauses

**Comment by mstackhouse** [comment]
In the example defines unfortunately I don't see any examples of OR statements, just compound ANDs.
![image](https://user-images.githubusercontent.com/31387567/174855518-3f3d73aa-7eac-422a-a2db-91304c03b797.png)

**Comment by statasaurus** [comment]
@CedricDavister I am going to break this issue into two. The first question about correct how compound where's are read in and the second question about the predecessor and assigned. I am just working through the second issue now and it should be available by the end of this week (maybe not for the define but 100% for the specs). Your example has made this much easier, thank you. 😃 

@mstackhouse Should we pull together a meeting to discuss the plan for how we change things for updating standards? I think there is probably more information I need to be able to figure out the best way to go with this.

**Comment by mstackhouse** [comment]
@statasaurus yes, I think we probably should because future-proofing that is relatively challenging.
