### ISSUE TITLE
dplyr 1.0.0 required?

### ISSUE THREAD

**Issue by bundfussr** [atorus-research/metacore#50]
It seems that metacore requires dplyr 1.0.0. I tried to use it with dplyr 0.8.5 and it failed. After updating dplyr to 1.0.9 it worked.

**Comment by mstackhouse** [comment]
@bundfussr can you send us the error that you encountered? We did a scrub for >=1.0.0 features a while ago so it would help to see your traceback of issues encountered.

**Comment by statasaurus** [comment]
I'll have a look at it next week

**Comment by rossfarrugia** [comment]
@statasaurus this one would be good to get resolved too if you get chance - any update?

**Comment by rossfarrugia** [comment]
Spoke to Mike and this one actually may no longer be needed from our perspective as we're not likely to be using pre 1.0.0 dplyr on our validated container.

**Comment by statasaurus** [comment]
Just FYI I am changing this over to xml2 from XML. I am just finishing up today. So it should be in dev by tomorrow.
