### ISSUE TITLE
Issue with our Roche DAP reader on latest dev version

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/metacore#54]
@statasaurus we had success using 0.0.4 version of metacore on CRAN, but when we tried our xls spec reader on latest 0.0.6 dev version we got:

_Caused by error in `.data$predecessor`:
! Column `predecessor` not found in `.data`._

I thought the latest updates were only focused on define.xml compatibility - did something else change around a "predecessor" field?? We'd need to account for this in our spec reader function in admiralroche.

**Comment by mstackhouse** [comment]
@statasaurus this has admittedly been way harder to trace than I feel like it should be. The lines that @rossfarrugia is encountering originate from the `refactor_define` branch. The thing is - I can't see in the history where that merged in to dev, but it originated in [this commit](https://github.com/atorus-research/metacore/tree/3326cd068e9471324adfcbbd733fb059963d3314). 

Just for notes - now I can see in [here](https://github.com/atorus-research/metacore/network) that `refactor_define` split from dev. But @statasaurus it looks like you made that commit directly on the dev branch. Moving forward we should only allow changes to dev through PRs. 

@Ross, the conversation around 'predecessor' originated in #49 for reference.

**Comment by mstackhouse** [comment]
But getting back to the discussion at hand - @rossfarrugia metacore did add a predecessor column based on the logic that in the define world, predecessor distinctly points at the originating variable, unlike other define origins that then leave the data information in a comment or derivation. So the idea was to add that column specifically so it could provide a link back to an originating variable. @statasaurus  correct me if I'm not explaining correctly but #49 is where that convo started. 

If Roche is actively using the dev branch and it's causing failures, let's make sure that we be more careful around the dev branch and get input before we merge in there.

**Comment by rossfarrugia** [comment]
@mstackhouse thanks for the explanation! we'll add something in our spec reader for this for later when this makes it to release. it was just one of our testers trying this out that noticed, as we'd usually only rely on the CRAN version. if any changes to metacore objects then appreciate any heads up as we just need to keep our Roche spec reader code aligned.

**Comment by statasaurus** [comment]
Sorry about not keeping you informed. But, now you understand can we close the issue?

**Comment by rossfarrugia** [comment]
yes np, thanks!
