### ISSUE TITLE
README: Installation of the current development version of metacore

### ISSUE THREAD

**Issue by esimms999-gsk** [atorus-research/metacore#55]
Is this misleading in that it loads the main branch and not the dev branch? 

<img width="821" alt="Screenshot 2022-09-16 104752" src="https://user-images.githubusercontent.com/85294667/190669282-ed629767-00f1-41d0-a73d-72e6d73ca2c2.png">

Maybe I am confused due to the admiral README instructions for loading the develoment version?

<img width="640" alt="Screenshot 2022-09-16 110423" src="https://user-images.githubusercontent.com/85294667/190670735-eaef5402-83bf-49f6-ad40-fdc72707df9e.png">

**Comment by statasaurus** [comment]
Not really. I tend to have the current development version on main. As long as that is stable. So I haven't pulled in some of the changes I have done into main cause they don't pass CMD checks. I let the CRAN copy be the stable release copy
