### ISSUE TITLE
Failure with dev tidyselect

### ISSUE THREAD

**Issue by hadley** [atorus-research/metacore#56]
With dev tidyselect there are a bunch of failures like:

```
Error (test-metacore.R:68:4): metacore wrapper function works
<dplyr:::mutate_error/rlang_error/error/condition>
Error in `mutate(., key_seq = str_split(key_seq, ",\\s"), key_seq = map(key_seq, 
    function(x) {
        tibble(variable = x) %>% mutate(key_seq = row_number())
    }))`: Problem while computing `key_seq = str_split(key_seq, ",\\s")`.
Caused by error in `vctrs::vec_size_common()`:
! object 'key_seq' not found
```

This comes down to a fairly subtle problem `create_tbl()` used a named argument to `tidyselect::matches()` which used to work by conicidence, but not longer does.

**Comment by hadley** [comment]
@statasaurus Just a note that I'm starting the release process for tidyselect with the goal of submitting to CRAN in two weeks, on October 10.

**Comment by statasaurus** [comment]
Wonderful! Thank you for giving me a heads up. I am doing updates now and should be all ready by then
