### ISSUE TITLE
yn_to_tf: additional fix needed

### ISSUE THREAD

**Issue by esimms999-gsk** [atorus-research/metacore#57]
Left is "main" branch, right is "dev" branch. The change was made to address Issue #47 . 

<img width="953" alt="Screenshot 2022-09-16 104705" src="https://user-images.githubusercontent.com/85294667/191020693-9f3f7c16-cb2f-4b28-a547-72c1333c7b14.png">

There needs to be an additional, small change made to the regex:

   if(all(is.na(x) | str_detect(x, regex("^y$|^n$|yes$|no$", ignore_case = T)))){
      case_when(str_detect(x, regex("^y$|yes$", ignore_case = T)) ~ TRUE,
                str_detect(x, regex("^n$|no$", ignore_case = T)) ~ FALSE,

"ABCy" would be set to NA. But "ABCyes" would be set to TRUE. Same with "ABCn" vs "ABCno" being set to NA vs FALSE.

**Comment by esimms999-gsk** [comment]
Created fork and PR #59 with modification to yn_to_tf in dev branch.

**Comment by mstackhouse** [comment]
Merged in #59 to dev
