### ISSUE TITLE
Export `create_tbl()`

### ISSUE THREAD

**Issue by thomas-neitmann** [atorus-research/metacore#6]
@statasaurus Thanks again for helping with building the Roche spec reader. After making some minor adjustments the reader now works properly and I incorporated it within an internal package. However, as the reader function makes use of the un-exported `create_tbl()` function I get a Note when running `R CMD check` which is not acceptable according to our package validation guidelines. Thus, please export this function. Thank you!

**Comment by mstackhouse** [comment]
@statasaurus I don't have any issue with exporting this. Any concerns from your side?
