### ISSUE TITLE
metacore fails if the value level is blank 

### ISSUE THREAD

**Issue by statasaurus** [atorus-research/metacore#64]
(Can use the r/pharma workshop excel to test this)

**Comment by kaz462** [comment]
Thanks, @statasaurus 
This issue is from `spec_type_to_derivations`: 
`ls_derivations %>%
	 reduce(bind_rows)` - cannot combine Variables$dataset \<character> and ValueLevel$dataset \<**logical**> due to different column types, because current blank columns are read as "logical" by default.

Potential resolution:
update `read_all_sheets` by adding col_types in `read_excel(...,  col_types = "text")`
