### ISSUE TITLE
Separate Warnings?

### ISSUE THREAD

**Issue by bundfussr** [atorus-research/metacore#70]
At the moment multiple issues are put into a single warning message. For example
```
Warning messages:
1: order from the ds_vars table only contain missing values.

keep from the ds_vars table only contain missing values.

supp_flag from the ds_vars table only contain missing values.

sig_dig from the value_spec table only contain missing values.

dataset from the supp table only contain missing values.

variable from the supp table only contain missing values.

idvar from the supp table only contain missing values.

qeval from the supp table only contain missing values.
```
This makes it hard to filter out warnings which are not of interest. For example, we have implemented a function to create a metacore object from the Roche standard specifications. As the Roche specs do not include significant digits, we would like to suppress the corresponding warning.

Could metacore create separate warnings for each detected issue?

Then it would be easy to suppress warnings which do not apply by calling `admiraldev::suppress_warning()`. For example:
```
  suppress_warning(
    metacore(
      ds_spec = ds_spec,
      ds_vars = ds_vars,
      var_spec = var_spec,
      value_spec = value_spec,
      derivations = derivations,
      codelist = codelist
    ),
    regexpr = "sig_dig from the value_spec table only contain missing values."
  )
```

**Comment by bundfussr** [comment]
@rossfarrugia, FYI

**Comment by rossfarrugia** [comment]
@statasaurus @mstackhouse do you think this request is feasible?

**Comment by statasaurus** [comment]
Hello, 
After speaking with my team we are going to leave this as a single warning because you are only calling a single function and we prefer a one warning per function approach. But, given this is a concern I am happy to put in a pull request to update the suppress_warning function. As it is a bit risking having that function remove the entire warning message when there is only a partial match.
